### ISSUE TITLE
好像没有解决翻页api的问题

### ISSUE THREAD

**Issue by hengnio** [AdNotFound/EhViewer#13]
### 复现步骤 / Steps to reproduce

直接从github上clone的代码后使用./gradlew app:assembleDebug进行APK封包。使用的SDK为Android 9 Pie

### 预期行为 / Expected behaviour

它应该修复了翻页API并且正常翻页

### 实际行为 / Actual behaviour

https://github.com/AdNotFound/EhViewer/assets/63005837/5dc405e7-cfb2-47e1-9502-48347b96be26

### EhViewer 版本号 / EhViewer version code

1.7.34.1

### EhViewer CI 版本 / EhViewer CI version

https://github.com/AdNotFound/EhViewer-Neko/actions/runs/6702044897/workflow

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 pro

### SoC 型号 / SoC model

高通骁龙855 八核

### 应用日志 / App logs

[log-2023-11-01-03-16-42-854.zip](https://github.com/AdNotFound/EhViewer/files/13220579/log-2023-11-01-03-16-42-854.zip)

### 自查步骤 / Self-review steps

- [X] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by AdNotFound** [comment]
暂时不知道是什么原因，可以先用里站或者挂梯子

**Comment by AdNotFound** [comment]
E-H(表)API问题已解决
[https://github.com/AdNotFound/EhViewer/commit/0ea4431bdbca28b194dd532651a9489a4cc29293](url)

**Comment by AdNotFound** [comment]
请更新该版本 [https://github.com/AdNotFound/EhViewer/actions/runs/6716256145](url)
